### ISSUE TITLE
Implement FS operations using the mmap lib

### ISSUE THREAD

**Issue by 19valeraNikitin96** [19valeraNikitin96/autumn_db#1]
Current implementation of FS library uses the basic File I/O. They do not provide high performance but it is a crucial moment for a database

Steps:
1) review the written code
2) try to run example (file is named as basic_operations.py)
3) implement FSOperationsImpl class

![image](https://github.com/19valeraNikitin96/autumn_db/assets/34107410/79dcdb2a-1615-4358-a90e-26c29f5b9cba)

**Comment by MarinaParkhomenko** [comment]
mmap allows you to access the file's contents using memory operations rather than traditional I/O operations. Here in _FSOperationsImpl_ two methods implement mmap - read and update. We cannot use mmap to create the files since the newly created file will be empty and it's not possible to memory map an empty file. Read implementation is pretty similar to the basic File I/O and the following update implementation allows to rewrite the content of the file.
